services:
  web:
    build: .
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn --bind 0.0.0.0:8000 app.wsgi:application
      "
    volumes:
      - .:/app  
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: "1"
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
